/*
 * Copyright (c) 2026 f78.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

import * as fs from "node:fs/promises";

import { colorSets } from "./_colors.ts";

// This script takes the colours imported above, generates a bunch of extra colour stops,
// and produces an SCSS module containing those colours, as well as maps for them.
//
// I did this because I felt the gaps between the colour stops were too big.
// Now I shouldn't run out of colours ever again.

type ColorPair = readonly [number, string];

function mix(previous: ColorPair, current: ColorPair, percent: number) {
	return [
		previous[0] + (current[0] - previous[0]) * percent,
		`color.mix(${current[1]}, ${previous[1]}, ${percent * 100}%, oklch)`,
	] as const;
}

let scss = `// Autogenerated by /scripts/prestart.ts, do not modify\n@use "sass:color";\n`;
for (const name in colorSets) {
	const set = colorSets[name];
	const colors: ColorPair[] = [
		[0, "white"],
		...Object.entries(set).map(([k, v]) => [parseInt(k), v] as const),
		[1000, "black"],
	];

	const fullSet: typeof colors = [];
	for (let i = 1; i < colors.length; i++) {
		const previous = colors[i - 1];
		const current = colors[i];

		// Blend the 2 colours
		fullSet.push(mix(previous, current, 0.25));
		fullSet.push(mix(previous, current, 0.5));
		fullSet.push(mix(previous, current, 0.75));

		if (i !== colors.length - 1) {
			fullSet.push(current);
		}
	}

	let scssMap = `\n$colors-${name}: (\n\t0: white,`;
	for (const [value, color] of fullSet) {
		scss += `\n$${name}-${Math.floor(value)}: ${color};`;
		scssMap += `\n\t${value}: ${color},`;
	}
	scss += `${scssMap}\n\t1000: black\n);\n`;
}

await fs.writeFile("./src/styles/_colors.scss", scss);
